"""
V12 笔记批量提炼 v2
使用预过滤文件列表 → DeepSeek ASR纠错+提取观点/金句/行动 → 写回vault
"""
import os
import re
import json
import time
import sys
from pathlib import Path

import requests

# ── Config ────────────────────────────────────────────
DEEPSEEK_API_KEY = os.environ.get("DEEPSEEK_API_KEY", "")
if not DEEPSEEK_API_KEY:
    raise RuntimeError("DEEPSEEK_API_KEY not set — set the env var and retry")
DEEPSEEK_URL = "https://api.deepseek.com/chat/completions"

VAULT_NOTES = Path(os.environ.get(
    "ARTHUR_NOTES_PATH",
    r"C:\Users\wanga\OneDrive\Documents\Obsidian Vault\Arthur-IP系统\笔记"
))

OUTPUT_DIR = Path(__file__).parent.parent / "output"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

PROGRESS_FILE = OUTPUT_DIR / "enrich_progress.json"
PENDING_LIST_FILE = OUTPUT_DIR / "pending_files.txt"

BATCH_SIZE = 5
BATCH_DELAY = 2  # seconds between batches
FILE_READ_RETRIES = 3
RETRY_DELAY = 2  # seconds between retries for hydration


# ── Enrichment Prompt ─────────────────────────────────
SYSTEM_PROMPT = """你是 Arthur 的内容提炼助手。处理抖音博主"99年的老男人"的视频转录文本。

任务：
1. 修正 ASR（语音识别）错误：
   - 同音错字：打满坟→打满分、乔不及→瞧不起、体谅→体量、语佛相来→与否向来、坦朋友→谈朋友、九肉→纠结、辞职力→执行力、上土鬼→洒脱点、抓翻→大方
   - 移除"1。2 3"等转录噪声标记
   - 修正断句错误
   - 繁体转简体

2. 提取 核心观点（3-5条，每条15字以内，短句punch风格）
   - 只提取有价值的商业/认知观点
   - 如果内容太水太碎，诚实返回 1-2 条即可

3. 提取 金句摘录（2-4条，原文中最扎心的句子）
   - 修正 ASR 错误后保留原意
   - 如果没有特别出彩的金句，可以不提取

4. 写 行动建议（1-3条，给 Arthur 的具体建议）
   - Arthur 是在苏里南的华人创业者，正在打造个人 IP
   - 如何把这条内容用到他的 X/Twitter 账号上
   - 如果跟苏里南无关，给通用社交媒体建议

输出格式（严格 JSON）：
```json
{
  "core_points": ["观点1", "观点2", "观点3"],
  "golden_quotes": ["金句1", "金句2"],
  "action_items": ["行动1", "行动2"],
  "thinking_model": "思维模型名称或空字符串",
  "corrected_transcript": "修正后的完整转录文本"
}
```"""


def load_progress() -> set:
    if PROGRESS_FILE.exists():
        try:
            return set(json.loads(PROGRESS_FILE.read_text(encoding="utf-8")))
        except json.JSONDecodeError:
            return set()
    return set()


def save_progress(done: set):
    PROGRESS_FILE.write_text(json.dumps(sorted(done), ensure_ascii=False), encoding="utf-8")


def load_pending_list() -> list[Path]:
    """Load pending file paths from pre-filtered list (generated by ripgrep)."""
    if not PENDING_LIST_FILE.exists():
        print("[WARN] pending_files.txt not found, regenerating...")
        return regenerate_pending_list()

    paths = []
    with open(PENDING_LIST_FILE, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#"):
                p = Path(line)
                # Handle relative paths (from ripgrep output)
                if not p.is_absolute():
                    p = VAULT_NOTES / p
                if p.exists():
                    paths.append(p)

    print(f"[INFO] Loaded {len(paths)} pending files from list")
    return paths


def regenerate_pending_list() -> list[Path]:
    """Fallback: scan vault for pending files (slower)."""
    import subprocess
    result = subprocess.run(
        ["rg", "-l", "--type", "md", "（待提取）", str(VAULT_NOTES)],
        capture_output=True, text=True, timeout=120
    )
    paths = []
    for line in result.stdout.strip().split("\n"):
        if line.strip():
            p = Path(line.strip())
            if not p.is_absolute():
                p = VAULT_NOTES / p
            if p.exists():
                paths.append(p)

    # Save for next time
    PENDING_LIST_FILE.write_text("\n".join(str(p) for p in paths), encoding="utf-8")
    print(f"📋 Regenerated list: {len(paths)} pending files")
    return paths


def read_file_with_retry(filepath: Path, retries: int = FILE_READ_RETRIES) -> str | None:
    """Read file content with retries for OneDrive hydration."""
    for attempt in range(retries):
        try:
            return filepath.read_text(encoding="utf-8")
        except OSError as e:
            if attempt < retries - 1:
                print(f"  ⏳ Hydrating... ({attempt+1}/{retries})", end=" ", flush=True)
                time.sleep(RETRY_DELAY)
            else:
                print(f"  ⚠️ Read failed after {retries} attempts: {e}")
                return None
    return None


def parse_note_for_enrichment(filepath: Path) -> dict:
    """Extract raw transcript from a note."""
    content = read_file_with_retry(filepath)
    if content is None:
        return {"transcript": "", "error": "read_error"}

    # Extract transcript from 详细内容 (V12-new) or 详细笔记 (V12-old)
    transcript = ""
    for pattern in [r"## 详细内容\s*\n(.*?)(?=\n##|\Z)", r"## 📝 详细笔记\s*\n(.*?)(?=\n##|\Z)"]:
        m = re.search(pattern, content, re.DOTALL)
        if m:
            transcript = m.group(1).strip()
            if len(transcript) >= 20:
                break

    if not transcript or len(transcript) < 20:
        return {"transcript": "", "error": "no_transcript"}

    return {"transcript": transcript[:3000], "content": content}


def enrich_note(filepath: Path) -> dict | None:
    """Run one note through DeepSeek enrichment."""
    parsed = parse_note_for_enrichment(filepath)
    if "error" in parsed:
        return parsed

    transcript = parsed["transcript"]

    try:
        resp = requests.post(
            DEEPSEEK_URL,
            headers={
                "Authorization": f"Bearer {DEEPSEEK_API_KEY}",
                "Content-Type": "application/json",
            },
            json={
                "model": "deepseek-chat",
                "messages": [
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": f"处理以下视频转录：\n\n{transcript}"},
                ],
                "temperature": 0.4,
                "max_tokens": 1500,
                "response_format": {"type": "json_object"},
            },
            timeout=90,
        )
        resp.raise_for_status()
        result = resp.json()["choices"][0]["message"]["content"]
        return json.loads(result)
    except json.JSONDecodeError:
        return {"error": "json_parse", "raw": str(result)[:200] if 'result' in dir() else ""}
    except requests.RequestException as e:
        return {"error": str(e)}


def apply_enrichment(filepath: Path, enrichment: dict):
    """Write enriched content back to the note."""
    content = read_file_with_retry(filepath)
    if content is None:
        print("  ⚠️ read error, skipping")
        return

    # Replace core points — handle both V12-new (## 核心观点) and V12-old (## 🎯 核心观点)
    cp_text = "\n".join(f"{i}. {p}" for i, p in enumerate(enrichment.get("core_points", []), 1))
    if cp_text:
        for pattern in [r"## 🎯 核心观点\s*\n.*?(?=\n##|\Z)", r"## 核心观点\s*\n.*?(?=\n##|\Z)"]:
            content, n = re.subn(pattern, f"## 核心观点\n\n{cp_text}\n", content, flags=re.DOTALL)
            if n > 0:
                break

    # Replace golden quotes
    quotes = enrichment.get("golden_quotes", [])
    if quotes:
        gq_text = "\n".join(f"> {q}" for q in quotes) + "\n"
        for pattern in [r"## 💡 金句摘录\s*\n.*?(?=\n##|\Z)", r"## 金句摘录\s*\n.*?(?=\n##|\Z)"]:
            content, n = re.subn(pattern, f"## 金句摘录\n\n{gq_text}\n", content, flags=re.DOTALL)
            if n > 0:
                break

    # Replace action items
    actions = enrichment.get("action_items", [])
    if actions:
        aa_text = "\n".join(actions)
        for pattern in [r"## 📌 行动建议\s*\n.*?(?=\n##|\Z)", r"## 行动建议\s*\n.*?(?=\n##|\Z)"]:
            content, n = re.subn(pattern, f"## 行动建议\n\n{aa_text}\n", content, flags=re.DOTALL)
            if n > 0:
                break

    # Replace thinking model
    model = enrichment.get("thinking_model", "")
    if model:
        for pattern in [r"## 🧠 思维模型\s*\n.*?(?=\n##|\Z)", r"## 思维模型\s*\n.*?(?=\n##|\Z)"]:
            content, n = re.subn(pattern, f"## 思维模型\n\n{model}\n", content, flags=re.DOTALL)
            if n > 0:
                break

    # Replace detail content with corrected transcript
    corrected = enrichment.get("corrected_transcript", "")
    if corrected:
        for pattern in [r"## 📝 详细笔记\s*\n.*?(?=\n##|\Z)", r"## 详细内容\s*\n.*?(?=\n##|\Z)"]:
            content, n = re.subn(pattern, f"## 详细内容\n\n{corrected}\n", content, flags=re.DOTALL)
            if n > 0:
                break

    # Normalize section headers to V12-new (remove emojis)
    content = re.sub(r"## 🎯 核心观点", "## 核心观点", content)
    content = re.sub(r"## 📝 详细笔记", "## 详细内容", content)
    content = re.sub(r"## 💡 金句摘录", "## 金句摘录", content)
    content = re.sub(r"## 📌 行动建议", "## 行动建议", content)
    content = re.sub(r"## 🧠 思维模型", "## 思维模型", content)

    # Write back
    try:
        filepath.write_text(content, encoding="utf-8")
    except OSError as e:
        print(f"  ⚠️ write error: {e}")


def process_batch():
    try:
        pending = load_pending_list()
    except Exception:
        pending = regenerate_pending_list()

    done = load_progress()

    # Filter out already processed
    remaining = [p for p in pending if str(p) not in done]
    total = len(remaining)

    if total == 0:
        print("✅ All notes completed!")
        return

    batches = total // BATCH_SIZE + 1
    print(f"📋 To process: {total} notes")
    print(f"📊 Batches: {batches} (size={BATCH_SIZE}, delay={BATCH_DELAY}s)")
    est_cost = total * 0.0002  # DeepSeek chat ~$0.20/1M tokens
    est_time = batches * (30 + BATCH_DELAY)  # ~30s per batch
    print(f"💰 Est. cost: ~${est_cost:.2f}")
    print(f"⏱️  Est. time: ~{est_time/60:.0f}min")
    print()

    processed = 0
    errors = 0

    for i in range(0, total, BATCH_SIZE):
        batch = remaining[i:i + BATCH_SIZE]
        batch_num = i // BATCH_SIZE + 1
        total_batches = (total + BATCH_SIZE - 1) // BATCH_SIZE

        for j, filepath in enumerate(batch):
            idx = i + j + 1
            name = filepath.stem[:60]
            cat = filepath.parent.name
            print(f"  [{idx}/{total}] [{batch_num}/{total_batches}] {cat}/{name}...", end=" ", flush=True)

            enrichment = enrich_note(filepath)

            if enrichment and "error" not in enrichment:
                try:
                    apply_enrichment(filepath, enrichment)
                    done.add(str(filepath))
                    processed += 1
                    cp_count = len(enrichment.get("core_points", []))
                    print(f"✅ ({cp_count} pts)")
                except Exception as e:
                    errors += 1
                    print(f"❌ write: {e}")
            else:
                errors += 1
                err = enrichment.get("error", "unknown") if enrichment else "no_result"
                print(f"❌ {err[:60]}")

        # Save progress after each batch
        save_progress(done)
        pct = processed / total * 100 if total > 0 else 0
        print(f"  💾 Batch {batch_num}/{total_batches} saved | {processed}/{total} ({pct:.1f}%) | {len(done)} total done")

        if i + BATCH_SIZE < total:
            print(f"  ⏸️  Waiting {BATCH_DELAY}s...")
            time.sleep(BATCH_DELAY)

    print(f"\n{'='*50}")
    print(f"✅ Complete! Success: {processed}, Errors: {errors}")
    print(f"💾 Progress: {PROGRESS_FILE}")


if __name__ == "__main__":
    process_batch()
